create table if not exists public.fundraising_donations (
  id bigint generated by default as identity primary key,
  amount integer not null check (amount > 0),
  donor_count integer not null default 0 check (donor_count >= 0),
  note text not null default '',
  date_label text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.fundraising_summary (
  id integer primary key default 1 check (id = 1),
  total_amount bigint not null default 0,
  donor_count bigint not null default 0,
  last_donation_amount integer not null default 0,
  last_updated_label text not null default '',
  updated_at timestamptz
);

insert into public.fundraising_summary (id)
values (1)
on conflict (id) do nothing;

create or replace function public.refresh_fundraising_summary()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  latest_record public.fundraising_donations%rowtype;
  total_amount_value bigint;
  donor_count_value bigint;
begin
  select
    coalesce(sum(amount), 0),
    coalesce(sum(donor_count), 0)
  into
    total_amount_value,
    donor_count_value
  from public.fundraising_donations;

  select *
  into latest_record
  from public.fundraising_donations
  order by updated_at desc, id desc
  limit 1;

  insert into public.fundraising_summary (
    id,
    total_amount,
    donor_count,
    last_donation_amount,
    last_updated_label,
    updated_at
  )
  values (
    1,
    total_amount_value,
    donor_count_value,
    coalesce(latest_record.amount, 0),
    coalesce(latest_record.date_label, ''),
    latest_record.updated_at
  )
  on conflict (id) do update
  set
    total_amount = excluded.total_amount,
    donor_count = excluded.donor_count,
    last_donation_amount = excluded.last_donation_amount,
    last_updated_label = excluded.last_updated_label,
    updated_at = excluded.updated_at;

  return null;
end;
$$;

drop trigger if exists trg_refresh_fundraising_summary on public.fundraising_donations;

create trigger trg_refresh_fundraising_summary
after insert or update or delete on public.fundraising_donations
for each statement
execute function public.refresh_fundraising_summary();

select public.refresh_fundraising_summary();

alter table public.fundraising_donations enable row level security;
alter table public.fundraising_summary enable row level security;

drop policy if exists "Public can read fundraising summary" on public.fundraising_summary;
create policy "Public can read fundraising summary"
on public.fundraising_summary
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage fundraising summary" on public.fundraising_summary;
create policy "Authenticated users can manage fundraising summary"
on public.fundraising_summary
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read donations" on public.fundraising_donations;
create policy "Authenticated users can read donations"
on public.fundraising_donations
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert donations" on public.fundraising_donations;
create policy "Authenticated users can insert donations"
on public.fundraising_donations
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can delete donations" on public.fundraising_donations;
create policy "Authenticated users can delete donations"
on public.fundraising_donations
for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can update donations" on public.fundraising_donations;
create policy "Authenticated users can update donations"
on public.fundraising_donations
for update
to authenticated
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'fundraising_summary'
  ) then
    alter publication supabase_realtime add table public.fundraising_summary;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'fundraising_donations'
  ) then
    alter publication supabase_realtime add table public.fundraising_donations;
  end if;
end $$;

*** Add File: C:\Users\User\Documents\_projects\SaouZADEV.github.io\supabase\README.md
# Supabase Setup

โปรเจกต์นี้ใช้ `Supabase Auth + Postgres + Realtime` กับหน้าเว็บ static บน GitHub Pages

## 1. สร้าง Supabase project

สร้างโปรเจกต์ใหม่ใน [Supabase Dashboard](https://supabase.com/dashboard/projects)

## 2. รัน SQL

เปิด `SQL Editor` แล้วรันไฟล์ [schema.sql](/C:/Users/User/Documents/_projects/SaouZADEV.github.io/supabase/schema.sql)

สิ่งที่จะถูกสร้าง:

- ตาราง `public.fundraising_donations`
- ตาราง `public.fundraising_summary`
- trigger ที่สรุปยอดให้อัตโนมัติเมื่อ insert / update / delete
- RLS policies
- realtime publication สำหรับ 2 ตารางนี้

## 3. สร้างผู้ใช้แอดมิน

เปิด `Authentication` แล้วสร้างผู้ใช้แบบ Email/Password สำหรับคนที่มีสิทธิ์อัปเดตยอด

คำแนะนำ:

- ปิด public signups ถ้าคุณไม่อยากให้ใครสมัครเพิ่มเอง
- ใช้บัญชีแอดมินเฉพาะสำหรับหน้า [admin.html](/C:/Users/User/Documents/_projects/SaouZADEV.github.io/admin.html)

## 4. คัดลอก Project URL และ anon key

เปิด `Project Settings` > `Data API`

คัดลอก:

- `Project URL`
- `anon / publishable key`

## 5. ใส่ค่าลง config

เปิด [fundraising-config.js](/C:/Users/User/Documents/_projects/SaouZADEV.github.io/fundraising-config.js) แล้วใส่ค่า:

```js
window.FUNDRAISING_CONFIG = {
  goalAmount: 1000000,
  supabase: {
    url: 'https://YOUR-PROJECT.supabase.co',
    anonKey: 'YOUR-ANON-KEY',
    summaryTable: 'fundraising_summary',
    donationsTable: 'fundraising_donations',
    summaryRowId: 1,
    enableRealtime: true,
    pollIntervalMs: 15000,
  },
};
```

## 6. วิธีใช้งาน

- หน้า [index.html](/C:/Users/User/Documents/_projects/SaouZADEV.github.io/index.html) อ่านสรุปยอดจาก `fundraising_summary`
- หน้า [admin.html](/C:/Users/User/Documents/_projects/SaouZADEV.github.io/admin.html) ใช้ Supabase Auth เพื่อ login
- เมื่อเพิ่มหรือลบรายการใน `fundraising_donations` trigger จะอัปเดต `fundraising_summary` ให้อัตโนมัติ

## หมายเหตุด้านความปลอดภัย

- หน้า public ใช้ `anon key` ได้ เพราะการอ่านถูกจำกัดด้วย RLS
- ตาราง `fundraising_donations` เปิดสิทธิ์เฉพาะ `authenticated`
- ถ้าคุณเปิดให้คนสมัครสมาชิกเอง ทุกคนที่ login ได้จะมีสิทธิ์จัดการยอดตาม policy ปัจจุบัน

ดังนั้นถ้าใช้ policy ชุดนี้:

- ปิด public signup
- สร้าง user แอดมินเองจาก dashboard เท่านั้น

## เอกสารทางการ

- [JavaScript client](https://supabase.com/docs/reference/javascript/installing)
- [Auth: signInWithPassword](https://supabase.com/docs/reference/javascript/auth-signinwithpassword)
- [Auth: onAuthStateChange](https://supabase.com/docs/reference/javascript/auth-onauthstatechange)
- [RLS](https://supabase.com/docs/guides/database/postgres/row-level-security)
- [Realtime Postgres Changes](https://supabase.com/docs/guides/realtime/postgres-changes)
