create table if not exists public.fundraising_donations (
  id bigint generated by default as identity primary key,
  amount integer not null check (amount > 0),
  donor_count integer not null default 0 check (donor_count >= 0),
  note text not null default '',
  date_label text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.fundraising_summary (
  id integer primary key default 1 check (id = 1),
  total_amount bigint not null default 0,
  donor_count bigint not null default 0,
  last_donation_amount integer not null default 0,
  last_updated_label text not null default '',
  updated_at timestamptz
);

insert into public.fundraising_summary (id)
values (1)
on conflict (id) do nothing;

create or replace function public.rebuild_fundraising_summary()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  latest_record public.fundraising_donations%rowtype;
  total_amount_value bigint;
  donor_count_value bigint;
begin
  select
    coalesce(sum(amount), 0),
    coalesce(sum(donor_count), 0)
  into
    total_amount_value,
    donor_count_value
  from public.fundraising_donations;

  select *
  into latest_record
  from public.fundraising_donations
  order by updated_at desc, id desc
  limit 1;

  insert into public.fundraising_summary (
    id,
    total_amount,
    donor_count,
    last_donation_amount,
    last_updated_label,
    updated_at
  )
  values (
    1,
    total_amount_value,
    donor_count_value,
    coalesce(latest_record.amount, 0),
    coalesce(latest_record.date_label, ''),
    latest_record.updated_at
  )
  on conflict (id) do update
  set
    total_amount = excluded.total_amount,
    donor_count = excluded.donor_count,
    last_donation_amount = excluded.last_donation_amount,
    last_updated_label = excluded.last_updated_label,
    updated_at = excluded.updated_at;

end;
$$;

create or replace function public.refresh_fundraising_summary()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.rebuild_fundraising_summary();
  return null;
end;
$$;

drop trigger if exists trg_refresh_fundraising_summary on public.fundraising_donations;

create trigger trg_refresh_fundraising_summary
after insert or update or delete on public.fundraising_donations
for each statement
execute function public.refresh_fundraising_summary();

select public.rebuild_fundraising_summary();

alter table public.fundraising_donations enable row level security;
alter table public.fundraising_summary enable row level security;

drop policy if exists "Public can read fundraising summary" on public.fundraising_summary;
create policy "Public can read fundraising summary"
on public.fundraising_summary
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can manage fundraising summary" on public.fundraising_summary;
create policy "Authenticated users can manage fundraising summary"
on public.fundraising_summary
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read donations" on public.fundraising_donations;
create policy "Authenticated users can read donations"
on public.fundraising_donations
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert donations" on public.fundraising_donations;
create policy "Authenticated users can insert donations"
on public.fundraising_donations
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can delete donations" on public.fundraising_donations;
create policy "Authenticated users can delete donations"
on public.fundraising_donations
for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can update donations" on public.fundraising_donations;
create policy "Authenticated users can update donations"
on public.fundraising_donations
for update
to authenticated
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'fundraising_summary'
  ) then
    alter publication supabase_realtime add table public.fundraising_summary;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'fundraising_donations'
  ) then
    alter publication supabase_realtime add table public.fundraising_donations;
  end if;
end $$;
